{{- if .Values.adService.create }}
  {{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{.Release.Namespace}}
  {{- if not .Values.serviceAccounts.annotationsOnlyForCartservice }}
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
---
  {{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adService.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.adService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          image: ahmad12abed/adservice:1.1.6
          ports:
            - containerPort: 9555
          env:
            - name: SL_TOKEN
              value: "{{ .Values.SealightsEnvVars.token }}"
            - name: SL_LAB_ID
              value: "{{ .Values.SealightsEnvVars.lab_id }}"
            - name: PORT
              value: "9555"
          resources:
            {{- toYaml .Values.adService.resources | nindent 10 }}
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.adService.name }}
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
  {{- if .Values.networkPolicies.create }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.adService.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontend.name }}
      ports:
        - port: 9555
          protocol: TCP
  egress:
    - {}
  {{- end }}
  {{- if .Values.sidecars.create }}
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  workloadSelector:
    labels:
      app: {{ .Values.adService.name }}
  egress:
    - hosts:
        - istio-system/*
      {{- if .Values.opentelemetryCollector.create }}
      - ./{{ .Values.opentelemetryCollector.name }}.{{ .Release.Namespace }}.svc.cluster.local
      {{- end }}
  {{- end }}
  {{- if .Values.authorizationPolicies.create }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adService.name }}
  rules:
    - from:
        - source:
            principals:
            {{- if .Values.serviceAccounts.create }}
            - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ .Values.frontend.name }}
            {{- else }}
            - cluster.local/ns/{{ .Release.Namespace }}/sa/default
            {{- end }}
      to:
        - operation:
            paths:
              - /hipstershop.AdService/GetAds
            methods:
              - POST
            ports:
              - "9555"
  {{- end }}
  {{- end }}
