{{- if .Values.sealightsService.create }}
{{- if .Values.serviceAccounts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sealightsService.name }}
  namespace: {{.Release.Namespace}}
  {{- if not .Values.serviceAccounts.annotationsOnlyForCartservice }}
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sealightsService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.sealightsService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.sealightsService.name }}
    spec:
      {{- if .Values.serviceAccounts.create }}
      serviceAccountName: {{ .Values.sealightsService.name }}
      {{- else }}
      serviceAccountName: default
      {{- end }}
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
        - name: regcred-mgmt
      containers:
      - name: server
        image: {{ .Values.images.repository }}/btq-{{ .Values.sealightsService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: 5732
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/sealights/sl-test-listener.jar -Dsl.token={{ .Values.SealightsEnvVars.token }} -Dsl.buildSessionIdFile=/sealights/buildSessionId.txt -Dsl.labId={{ .Values.SealightsEnvVars.lab_id }}"
        - name: PORT
          value: "5732"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sealightsService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.sealightsService.name }}
  ports:
  - name: grpc
    port: 5732
    targetPort: 5732
{{- if .Values.networkPolicies.create }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.sealightsService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.sealightsService.name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  # - from:
  #   - podSelector:
  #       matchLabels:
  #         app: {{ .Values.frontend.name }}
    ports:
     - port: 5732
       protocol: TCP
  egress:
  - {}
{{- end }}
{{- end }}
