apiVersion: v1
kind: Pod
metadata:
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
spec:
  serviceAccount: jenkins-service-account
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.13.3-1
      workingDir: /home/jenkins/agent
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
      resources:
        requests:
          cpu: 1.5
          memory: 1500Mi
          ephemeral-storage: 2500Mi
        limits:
          cpu: 5
          memory: 7000Mi
          ephemeral-storage: 8000Mi
      securityContext:
        privileged: true
    - name: shell
      image: 534369319675.dkr.ecr.us-west-2.amazonaws.com/sl-jenkins-all-in:latest
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 2000Mi
          cpu: 2
          ephemeral-storage: 3000Mi
        limits:
          memory: 7500Mi
          cpu: 5
          ephemeral-storage: 7500Mi
  nodeSelector:
    type: jenkins
