apiVersion: v1
kind: Pod

spec:
  serviceAccount: jenkins-service-account
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.11.2-4
      workingDir: /home/jenkins/agent
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
      resources:
        requests:
          cpu: 200m
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 512m
          memory: 512Mi
          ephemeral-storage: 200Mi
      securityContext:
        privileged: true
    - name: shell
      image: 534369319675.dkr.ecr.us-west-2.amazonaws.com/sl-jenkins-python:latest
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 600Mi
          cpu: 1
          ephemeral-storage: 500Mi
        limits:
          memory: 1000Mi
          cpu: 1.5
          ephemeral-storage: 2000Mi
  nodeSelector:
    type: nightly
