apiVersion: v1
kind: Pod
spec:
  serviceAccount: jenkins-service-account
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:4.13.3-1
      workingDir: /home/jenkins/agent
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080/"
      resources:
        requests:
          cpu: 2.5
          memory: 350Mi
          ephemeral-storage: 150Mi
        limits:
          cpu: 4
          memory: 512Mi
          ephemeral-storage: 1500Mi
        limits:
          cpu: 5
          memory: 5120Mi
          ephemeral-storage: 2000Mi
      securityContext:
        privileged: true
    - name: shell
      image: 534369319675.dkr.ecr.us-west-2.amazonaws.com/sl-jenkins-base-ci:latest
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 1000Mi
          cpu: 2.5
          ephemeral-storage: 2000Mi
        limits:
          memory: 2000Mi
          cpu: 5
          ephemeral-storage: 10000Mi
  nodeSelector:
    type: jenkins
